spring:
  h2:
    console:
      enabled: true
      # path: /h2-console
  datasource:
    platform: h2
    url: jdbc:h2:mem:testdb
#    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
#    username: sa
#    password:
    schema: classpath:/schema.sql
    data: classpath:/data.sql
    sql-script-encoding: UTF-8
    # embedded always
    initialization-mode: always
# debug: true # Enable debug logs.
#trace=false # Enable trace logs.
logging:
 level:
   org:
     ysp: debug